# Generated by Django 5.2 on 2026-07-25 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_customeraddress_lat_alter_customeraddress_lng_and_more'),
        ('existedservices', '0016_alter_previouswork_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueCollectionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Due Collection Batch',
                'db_table': 'due_collection_batches',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payout Batch',
                'db_table': 'payout_batches',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='DueCollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('moyasar_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.duecollectionbatch')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_collection_items', to='accounts.provider')),
            ],
            options={
                'verbose_name': 'Due Collection Item',
                'db_table': 'due_collection_items',
                'unique_together': {('batch', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('awaiting_method', 'Awaiting Method'), ('awaiting_gateway_payment', 'Awaiting Gateway Payment'), ('awaiting_cash_confirmation', 'Awaiting Cash Confirmation'), ('paid', 'Paid'), ('failed', 'Failed')], default='awaiting_method', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completion_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to='existedservices.servicecompletionform')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'db_table': 'payment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlinePaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moyasar_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('raw_callback_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_attempts', to='payments.paymentrequest')),
            ],
            options={
                'verbose_name': 'Online Payment Attempt',
                'db_table': 'online_payment_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transferred', 'Transferred'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reference_note', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.payoutbatch')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_items', to='accounts.provider')),
            ],
            options={
                'verbose_name': 'Payout Batch Item',
                'db_table': 'payout_batch_items',
                'unique_together': {('batch', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ProviderDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due', to='accounts.provider')),
            ],
            options={
                'verbose_name': 'Provider Due',
                'db_table': 'provider_dues',
            },
        ),
        migrations.CreateModel(
            name='DueTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('reversal', 'Reversal')], max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_transactions', to='payments.duecollectionitem')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_transactions', to='payments.paymentrequest')),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.providerdue')),
            ],
            options={
                'verbose_name': 'Due Transaction',
                'db_table': 'due_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.provider')),
            ],
            options={
                'verbose_name': 'Provider Wallet',
                'db_table': 'provider_wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('commission_credit', 'Commission Credit'), ('payout_debit', 'Payout Debit'), ('reversal', 'Reversal')], max_length=20)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.payoutbatchitem')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='payments.paymentrequest')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.providerwallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
