# Generated by Django 5.2 on 2026-07-26 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customeraddress_lat_alter_customeraddress_lng_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='points_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='points_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_redeemed_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_wallet', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Customer Points Wallet',
                'db_table': 'customer_point_wallets',
            },
        ),
        migrations.CreateModel(
            name='CustomerPointsTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('earned_pending', 'Earned (Pending)'), ('earned_credited', 'Earned (Credited)'), ('redeemed', 'Redeemed'), ('refunded', 'Refunded')], max_length=20)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='payments.paymentrequest')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.customerwallet')),
            ],
            options={
                'verbose_name': 'Customer Points Transaction',
                'db_table': 'customer_points_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsMarketingExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_expense', to='payments.paymentrequest')),
            ],
            options={
                'verbose_name': 'Points Marketing Expense',
                'db_table': 'points_marketing_expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
