# Generated by Django 5.2 on 2026-08-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentrequest_points_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='marketing_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
