# Generated by Django 5.2 on 2026-07-05 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=20)),
                ('recipient_id', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('new_custom_request', 'New Custom Request'), ('new_offer', 'New Offer'), ('offer_accepted', 'Offer Accepted'), ('new_chat_message', 'New Chat Message')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='requestchat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestchat',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='requestchat',
            index=models.Index(fields=['request', 'sender_type', 'is_read'], name='request_cha_request_5bf9af_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_type', 'recipient_id', 'is_read'], name='notificatio_recipie_651bd8_idx'),
        ),
    ]
