# Generated by Django 5.2 on 2026-07-05 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0002_notification_requestchat_is_read_requestchat_read_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=20)),
                ('recipient_id', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device_tokens',
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id'], name='device_toke_recipie_981144_idx')],
            },
        ),
    ]
