# Generated by Django 5.2 on 2026-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0003_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('new_custom_request', 'New Custom Request'), ('new_offer', 'New Offer'), ('offer_accepted', 'Offer Accepted'), ('new_chat_message', 'New Chat Message'), ('payment_received', 'Payment Received'), ('due_payment_required', 'Due Payment Required'), ('account_unblocked', 'Account Unblocked')], max_length=30),
        ),
    ]
