# Generated by Django 5.2 on 2026-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0004_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('new_custom_request', 'New Custom Request'), ('new_offer', 'New Offer'), ('offer_accepted', 'Offer Accepted'), ('new_chat_message', 'New Chat Message'), ('payment_received', 'Payment Received'), ('due_payment_required', 'Due Payment Required'), ('account_unblocked', 'Account Unblocked'), ('payment_required', 'Payment Required'), ('points_credited', 'Points Credited')], max_length=30),
        ),
    ]
