# Generated by Django 5.2 on 2026-08-09 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0005_alter_notification_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequestImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='custom_services.customrequest')),
            ],
            options={
                'verbose_name': 'Custom Request Image',
                'db_table': 'custom_request_images',
                'ordering': ['created_at'],
            },
        ),
    ]
