# Generated by Django 5.2 on 2026-08-09 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0006_customrequestimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Slide',
                'db_table': 'onboarding_slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
