# Generated by Django 5.2 on 2026-08-09 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0007_onboardingslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Message',
                'db_table': 'app_messages',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
