# Generated by Django 5.2 on 2026-09-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0008_appmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestchat',
            name='attachment_duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدة الرسالة الصوتية بالثواني', null=True),
        ),
        migrations.AddField(
            model_name='requestchat',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestchat',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestchat',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='حجم الملف بالبايت', null=True),
        ),
        migrations.AddField(
            model_name='requestchat',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('voice', 'Voice Note'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='requestchat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
