# Generated by Django 5.2 on 2026-05-19 10:41

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to='accounts.admin'),
        ),
        migrations.CreateModel(
            name='BiometricToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider')], max_length=20)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'biometric_tokens',
                'unique_together': {('user_id', 'user_type', 'device_id')},
            },
        ),
    ]
