# Generated by Django 5.2 on 2026-05-19 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_admin_created_by_biometrictoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('building_no', models.CharField(blank=True, max_length=20)),
                ('floor_no', models.CharField(blank=True, max_length=10)),
                ('apartment_no', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(blank=True, help_text='مثال: البيت، الشغل', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'db_table': 'customer_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
