# Generated by Django 5.2 on 2026-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_specialization_alter_provider_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
