# Generated by Django 5.2 on 2026-06-03 19:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customeraddress_region_provider_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'City',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='provider',
            name='city',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='district',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='region',
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_addresses', to='accounts.city'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='accounts.city')),
            ],
            options={
                'verbose_name': 'Region',
                'db_table': 'regions',
                'ordering': ['name'],
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='ProviderAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('building_no', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_addresses', to='accounts.city')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.provider')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_addresses', to='accounts.region')),
            ],
            options={
                'verbose_name': 'Provider Address',
                'db_table': 'provider_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_addresses', to='accounts.region'),
        ),
    ]
