# Generated by Django 5.2 on 2026-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_city_remove_provider_city_remove_provider_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
