# Generated by Django 5.2 on 2026-06-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_device_token_provider_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
    ]
