# Generated by Django 5.2 on 2026-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customeraddress_lat_customeraddress_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
