# Generated by Django 5.2 on 2026-06-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customeraddress_lat_alter_customeraddress_lng'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='previouswork',
            table='provider_previous_works',
        ),
    ]
