# Generated by Django 5.2 on 2026-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_previouswork_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideraddress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='provideraddress',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
