# Generated by Django 5.2 on 2026-08-02 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customeraddress_lat_alter_customeraddress_lng_and_more'),
        ('payments', '0003_paymentrequest_marketing_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marketing Code',
                'verbose_name_plural': 'Marketing Codes',
                'db_table': 'marketing_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_discount_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='signup_marketing_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_up_customers', to='accounts.marketingcode'),
        ),
        migrations.CreateModel(
            name='MarketingCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_code_usage', to='accounts.customer')),
                ('marketing_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.marketingcode')),
                ('payment_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_code_usage', to='payments.paymentrequest')),
            ],
            options={
                'verbose_name': 'Marketing Code Usage',
                'db_table': 'marketing_code_usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
