# Generated by Django 5.2 on 2026-09-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_marketingcode_customer_marketing_discount_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
