# Generated by Django 5.2 on 2026-09-14 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customer_photo_provider_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=34)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.provider')),
            ],
            options={
                'verbose_name': 'Provider Bank Account',
                'verbose_name_plural': 'Provider Bank Accounts',
                'db_table': 'provider_bank_accounts',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
