# Generated by Django 5.2 on 2026-05-20 13:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_previouswork_review'),
        ('existedservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.provider'),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='accounts.provider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='existedservices.existedservice')),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'db_table': 'service_providers',
                'ordering': ['created_at'],
                'unique_together': {('service', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='existedservices.existedservice')),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'db_table': 'service_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('service', 'customer')},
            },
        ),
    ]
