# Generated by Django 5.2 on 2026-05-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_previouswork_review'),
        ('existedservices', '0002_booking_provider_serviceprovider_servicereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.customeraddress'),
        ),
    ]
