# Generated by Django 5.2 on 2026-05-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_specialization_alter_provider_specialization'),
        ('existedservices', '0003_alter_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='existedservice',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='accounts.specialization'),
        ),
    ]
