# Generated by Django 5.2 on 2026-05-24 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0004_existedservice_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_value', models.PositiveIntegerField()),
                ('duration_type', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='existedservices.existedservice')),
            ],
            options={
                'verbose_name': 'Warranty',
                'verbose_name_plural': 'Warranties',
                'db_table': 'warranties',
                'ordering': ['-created_at'],
            },
        ),
    ]
