# Generated by Django 5.2 on 2026-05-24 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0005_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCompletionForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_form', to='existedservices.booking')),
            ],
            options={
                'verbose_name': 'Service Completion Form',
                'db_table': 'service_completion_forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletionMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='existedservices.servicecompletionform')),
            ],
            options={
                'verbose_name': 'Completion Media',
                'db_table': 'completion_media',
                'ordering': ['created_at'],
            },
        ),
    ]
