# Generated by Django 5.2 on 2026-05-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_services', '0001_initial'),
        ('existedservices', '0008_booking_coupon_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecompletionform',
            name='custom_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_form', to='custom_services.customrequest'),
        ),
    ]
