# Generated by Django 5.2 on 2026-06-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0009_servicecompletionform_custom_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceattribute',
            name='quantity_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceattribute',
            name='unit_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
