# Generated by Django 5.2 on 2026-06-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0010_serviceattribute_quantity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existedservice',
            name='visit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
