# Generated by Django 5.2 on 2026-06-22 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0011_existedservice_visit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('before_image', models.URLField()),
                ('after_image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completion_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_work', to='existedservices.servicecompletionform')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_works', to='existedservices.existedservice')),
            ],
            options={
                'verbose_name': 'Previous Work',
                'db_table': 'service_previous_works',
                'ordering': ['-created_at'],
            },
        ),
    ]
