# Generated by Django 5.2 on 2026-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0012_previouswork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouswork',
            name='after_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previouswork',
            name='before_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
