# Generated by Django 5.2 on 2026-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0013_alter_previouswork_after_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecompletionform',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecompletionform',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('provider_arrived', 'Provider Arrived')], default='waiting', max_length=20),
        ),
    ]
