# Generated by Django 5.2 on 2026-07-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0014_servicecompletionform_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecompletionform',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_form', to='existedservices.booking'),
        ),
    ]
