# Generated by Django 5.2 on 2026-07-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0015_alter_servicecompletionform_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouswork',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_works', to='existedservices.existedservice'),
        ),
    ]
