# Generated by Django 5.2 on 2026-08-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existedservices', '0016_alter_previouswork_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='serviceattribute',
            name='quantity_name',
        ),
        migrations.RemoveField(
            model_name='serviceattribute',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='serviceattribute',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='priced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_price', 'Awaiting Price'), ('price_proposed', 'Price Proposed'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='BookingItem',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
